# Generated by Django 3.0 on 2020-05-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0014_apoderado_sumado'),
        ('eventos', '0008_auto_20200518_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha_hora')),
                ('asambleista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asambleista', to='usuarios.Asambleista')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaAbierta',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='respuestas.Respuesta')),
                ('respuesta_texto', models.TextField(blank=True, default='', max_length=512)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_abierta', to='eventos.PreguntaAbierta')),
            ],
            bases=('respuestas.respuesta',),
        ),
    ]
