# Generated by Django 3.0 on 2020-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha_hora'),
        ),
    ]
