# Generated by Django 3.0 on 2020-05-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_pregunta_bloquea_mora'),
        ('respuestas', '0005_auto_20200521_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaOpMultiple',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='respuestas.Respuesta')),
                ('opciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcion_multiple', to='eventos.OpcionesMultiple')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_multiple', to='eventos.PreguntaMultiple')),
            ],
            bases=('respuestas.respuesta',),
        ),
    ]
