# Generated by Django 3.0 on 2020-05-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_pregunta_bloquea_mora'),
        ('respuestas', '0006_respuestaopmultiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaopmultiple',
            name='opciones',
        ),
        migrations.AddField(
            model_name='respuestaopmultiple',
            name='opciones',
            field=models.ManyToManyField(related_name='opcion_multiple', to='eventos.OpcionesMultiple'),
        ),
    ]
