# Generated by Django 3.0 on 2020-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0007_auto_20200527_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaopmultiple',
            name='coeficientes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
