# Generated by Django 3.0 on 2020-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0008_respuestaopmultiple_coeficientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaopmultiple',
            name='coeficientes',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
