# Generated by Django 3.0 on 2020-06-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0009_auto_20200602_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaopmultiple',
            name='votos',
            field=models.IntegerField(null=True),
        ),
    ]
