# Generated by Django 3.0 on 2020-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('bodyCorreo', models.CharField(max_length=3000)),
                ('linkEvento', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
