# Generated by Django 3.0 on 2020-05-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_pregunta_preguntaabierta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaDecimal',
            fields=[
                ('pregunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pregunta')),
            ],
            bases=('eventos.pregunta',),
        ),
    ]
