# Generated by Django 3.0 on 2020-05-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_preguntadecimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaMultiple',
            fields=[
                ('pregunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pregunta')),
                ('esMultipleResp', models.BooleanField()),
                ('respuestasPermitidas', models.IntegerField(default=1)),
            ],
            bases=('eventos.pregunta',),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.Evento'),
        ),
        migrations.CreateModel(
            name='OpcionesMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=500)),
                ('preguntaSeleccionMultiple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='eventos.PreguntaMultiple')),
            ],
        ),
    ]
