# Generated by Django 3.0 on 2020-05-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200516_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='linkEvento',
            field=models.CharField(max_length=300),
        ),
    ]
