# Generated by Django 3.0 on 2020-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200518_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntadecimal',
            name='maximo',
            field=models.IntegerField(default=5, verbose_name='valor_maximo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntadecimal',
            name='minimo',
            field=models.IntegerField(default=1, verbose_name='valor_minimo'),
            preserve_default=False,
        ),
    ]
