# Generated by Django 3.0 on 2020-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20200521_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='bloquea_mora',
            field=models.BooleanField(default=False),
        ),
    ]
