# Generated by Django 3.0 on 2020-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_preguntamultiple_strictmax'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='numeracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntamultiple',
            name='opPresentacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
