# Generated by Django 3.0 on 2020-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20200528_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='regitroQuorum',
            field=models.BooleanField(default=True),
        ),
    ]
