# Generated by Django 3.0 on 2020-05-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_evento_regitroquorum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='regitroQuorum',
            field=models.BooleanField(default=False),
        ),
    ]
