# Generated by Django 3.0 on 2020-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_auto_20200529_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
