# Generated by Django 3.0 on 2020-06-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_auto_20200529_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntamultiple',
            name='esMultipleResp',
            field=models.BooleanField(default=True),
        ),
    ]
