# Generated by Django 3.0 on 2020-06-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20200531_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='logo_asamblea',
            field=models.ImageField(null=True, upload_to='', verbose_name='logo'),
        ),
    ]
