# Generated by Django 3.0 on 2020-06-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_evento_logo_asamblea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='logo_asamblea',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='logo'),
        ),
    ]
