# Generated by Django 3.0 on 2020-06-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_auto_20200601_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_conferencia',
            field=models.URLField(null=True, verbose_name='link_conferencia'),
        ),
    ]
