# Generated by Django 3.0 on 2020-06-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='quorum',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
        ),
        migrations.CreateModel(
            name='Quorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente_total', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('coeficiente_registrado', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='fecha_hora_registro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_quorum', to='eventos.Evento')),
            ],
        ),
    ]
