# Generated by Django 3.0 on 2020-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_auto_20200602_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quorum',
            name='coeficiente_registrado',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quorum',
            name='coeficiente_total',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
            preserve_default=False,
        ),
    ]
