# Generated by Django 3.0 on 2020-06-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_auto_20200602_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cantidadQuorum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quorum',
            name='cantidadPersonas',
            field=models.IntegerField(default=0),
        ),
    ]
