# Generated by Django 3.0 on 2020-06-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_auto_20200607_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='codConferencia',
            field=models.CharField(max_length=150, null=True, verbose_name='codigo_conferencia'),
        ),
    ]
