# Generated by Django 3.0 on 2020-06-30 00:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_evento_codconferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='quorum',
            name='imuebles_registrados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
