# Generated by Django 3.0 on 2020-06-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_asambleista_propietario'),
        ('eventos', '0029_quorum_imuebles_registrados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quorum',
            name='imuebles_registrados',
        ),
        migrations.AddField(
            model_name='quorum',
            name='imuebles_registrados',
            field=models.ManyToManyField(related_name='inmuebles_presentes', to='usuarios.Asambleista'),
        ),
    ]
