# Generated by Django 3.0 on 2020-07-02 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_quorum_imuebles_registrados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quorum',
            name='imuebles_registrados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=4, null=True), size=None),
        ),
    ]
