# Generated by Django 3.0 on 2020-06-30 05:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_auto_20200629_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quorum',
            name='imuebles_registrados',
        ),
        migrations.AddField(
            model_name='quorum',
            name='imuebles_registrados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=None, size=None),
            preserve_default=False,
        ),
    ]
