# Generated by Django 3.0 on 2021-02-21 23:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_auto_20200705_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblesquorum',
            name='inmuebles_registrados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=150, null=True), blank=True, null=True, size=None),
        ),
    ]
