# Generated by Django 3.0 on 2020-06-30 05:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_auto_20200630_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quorum',
            name='imuebles_registrados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4, null=True), size=None),
        ),
    ]
