# Generated by Django 3.0 on 2020-05-18 14:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200518_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asambleista',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='asambleista',
            name='mora',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
