# Generated by Django 3.0 on 2020-05-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200518_0055'),
        ('usuarios', '0004_auto_20200518_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asambleista',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='asambleista',
            name='mora',
            field=models.BooleanField(default=False),
        ),
    ]
