# Generated by Django 3.0 on 2020-05-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200518_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asambleista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Asambleista')),
            ],
            options={
                'verbose_name': 'apoderado',
                'verbose_name_plural': 'apoderados',
            },
        ),
    ]
