# Generated by Django 3.0 on 2020-05-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200519_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='representado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Asambleista'),
        ),
    ]
