# Generated by Django 3.0 on 2020-05-19 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_apoderado_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='documento_poder',
            field=models.FileField(blank=True, upload_to='poderes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'JPEG', 'JPG', 'PNG', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
