# Generated by Django 3.0 on 2020-05-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20200521_1930'),
        ('usuarios', '0014_apoderado_sumado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
            preserve_default=False,
        ),
    ]
