# Generated by Django 3.0 on 2020-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20200525_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asambleista',
            name='inmueble',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
