# Generated by Django 3.0 on 2020-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20200527_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
