# Generated by Django 3.0 on 2020-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20200528_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='asambleista',
            name='quorumStatus',
            field=models.BooleanField(default=False),
        ),
    ]
