# Generated by Django 3.0 on 2020-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_asambleista_quorumstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asambleista',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
