# Generated by Django 3.0 on 2020-05-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20200529_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='asambleista',
            name='nombre_completo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
