# Generated by Django 3.0 on 2020-06-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20200531_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asambleista',
            name='coeficiente',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
