# Generated by Django 3.0 on 2020-06-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_auto_20200602_0803'),
        ('usuarios', '0024_asambleista_correo_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asambleista',
            name='coeficientePoderesDia',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='asambleista',
            name='coeficienteTotal',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poder_evento', to='eventos.Evento'),
        ),
    ]
