# Generated by Django 3.0 on 2020-07-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_asambleista_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='externo',
            field=models.BooleanField(default=False),
        ),
    ]
