# Generated by Django 3.0 on 2020-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_apoderado_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asambleista',
            name='celular',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='asambleista',
            name='documento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
